// Curated Iconify catalog for the admin picker.
// Values are saved as "iconify:<set>:<name>" in data/events.json.
(function () {
  var icons = [
    { value: 'iconify:fa6-solid:mountain', label: 'Mountain', set: 'Font Awesome', category: 'basic', tags: ['intro', 'journey', 'challenge', 'outdoors'] },
    { value: 'iconify:fa6-solid:star', label: 'Star', set: 'Font Awesome', category: 'basic', tags: ['highlight', 'favorite', 'milestone'] },
    { value: 'iconify:fa6-solid:heart', label: 'Heart', set: 'Font Awesome', category: 'life', tags: ['love', 'family', 'care'] },
    { value: 'iconify:fa7-regular:hand-point-right', label: 'Hand Point Right', set: 'Font Awesome 7', category: 'basic', tags: ['point', 'pointer', 'direction', 'next', 'intro'] },
    { value: 'iconify:fa6-solid:lightbulb', label: 'Lightbulb', set: 'Font Awesome', category: 'pivotal', tags: ['idea', 'learning', 'insight'] },
    { value: 'iconify:fa6-solid:graduation-cap', label: 'Graduation Cap', set: 'Font Awesome', category: 'work', tags: ['school', 'education', 'learning'] },
    { value: 'iconify:fa6-solid:book', label: 'Book', set: 'Font Awesome', category: 'passion', tags: ['reading', 'writing', 'knowledge'] },
    { value: 'iconify:fa6-solid:briefcase', label: 'Briefcase', set: 'Font Awesome', category: 'work', tags: ['career', 'job', 'business'] },
    { value: 'iconify:fa6-solid:code', label: 'Code', set: 'Font Awesome', category: 'work', tags: ['software', 'development', 'technology'] },
    { value: 'iconify:fa6-solid:rocket', label: 'Rocket', set: 'Font Awesome', category: 'work', tags: ['launch', 'startup', 'growth'] },
    { value: 'iconify:fa6-solid:flag', label: 'Flag', set: 'Font Awesome', category: 'pivotal', tags: ['goal', 'country', 'marker'] },
    { value: 'iconify:fa6-solid:trophy', label: 'Trophy', set: 'Font Awesome', category: 'work', tags: ['award', 'achievement', 'win'] },
    { value: 'iconify:fa6-solid:medal', label: 'Medal', set: 'Font Awesome', category: 'work', tags: ['award', 'recognition', 'sport'] },
    { value: 'iconify:fa6-solid:crown', label: 'Crown', set: 'Font Awesome', category: 'work', tags: ['leadership', 'achievement'] },
    { value: 'iconify:fa6-solid:bolt', label: 'Bolt', set: 'Font Awesome', category: 'pivotal', tags: ['energy', 'change', 'spark'] },
    { value: 'iconify:fa6-solid:fire', label: 'Fire', set: 'Font Awesome', category: 'pivotal', tags: ['intensity', 'passion', 'drive'] },
    { value: 'iconify:fa6-solid:globe', label: 'Globe', set: 'Font Awesome', category: 'pivotal', tags: ['world', 'travel', 'global'] },
    { value: 'iconify:fa6-solid:plane', label: 'Plane', set: 'Font Awesome', category: 'life', tags: ['travel', 'move', 'flight'] },
    { value: 'iconify:fa6-solid:map', label: 'Map', set: 'Font Awesome', category: 'life', tags: ['travel', 'place', 'journey'] },
    { value: 'iconify:fa6-solid:location-dot', label: 'Location Dot', set: 'Font Awesome', category: 'life', tags: ['place', 'map', 'home'] },
    { value: 'iconify:fa6-solid:house', label: 'House', set: 'Font Awesome', category: 'life', tags: ['home', 'family', 'move'] },
    { value: 'iconify:fa6-solid:people-group', label: 'People Group', set: 'Font Awesome', category: 'life', tags: ['team', 'community', 'family'] },
    { value: 'iconify:fa6-solid:handshake', label: 'Handshake', set: 'Font Awesome', category: 'work', tags: ['partnership', 'agreement', 'work'] },
    { value: 'iconify:fa6-solid:comments', label: 'Comments', set: 'Font Awesome', category: 'passion', tags: ['conversation', 'community', 'social'] },
    { value: 'iconify:fa6-solid:camera', label: 'Camera', set: 'Font Awesome', category: 'passion', tags: ['photo', 'memory', 'media'] },
    { value: 'iconify:fa6-solid:film', label: 'Film', set: 'Font Awesome', category: 'passion', tags: ['video', 'story', 'media'] },
    { value: 'iconify:fa6-solid:music', label: 'Music', set: 'Font Awesome', category: 'passion', tags: ['song', 'creative', 'art'] },
    { value: 'iconify:fa6-solid:palette', label: 'Palette', set: 'Font Awesome', category: 'passion', tags: ['art', 'creative', 'design'] },
    { value: 'iconify:fa6-solid:pen', label: 'Pen', set: 'Font Awesome', category: 'passion', tags: ['writing', 'author', 'notes'] },
    { value: 'iconify:fa6-solid:hammer', label: 'Hammer', set: 'Font Awesome', category: 'passion', tags: ['making', 'building', 'tools'] },
    { value: 'iconify:fa6-solid:wrench', label: 'Wrench', set: 'Font Awesome', category: 'passion', tags: ['repair', 'tools', 'making'] },
    { value: 'iconify:fa6-solid:box', label: 'Box', set: 'Font Awesome', category: 'passion', tags: ['crate', 'package', 'making'] },
    { value: 'iconify:fa6-solid:gift', label: 'Gift', set: 'Font Awesome', category: 'life', tags: ['present', 'celebration'] },
    { value: 'iconify:fa6-solid:calendar', label: 'Calendar', set: 'Font Awesome', category: 'basic', tags: ['date', 'event', 'time'] },
    { value: 'iconify:fa6-solid:clock', label: 'Clock', set: 'Font Awesome', category: 'basic', tags: ['time', 'history', 'moment'] },
    { value: 'iconify:fa6-solid:anchor', label: 'Anchor', set: 'Font Awesome', category: 'life', tags: ['stability', 'sea', 'place'] },
    { value: 'iconify:fa6-solid:leaf', label: 'Leaf', set: 'Font Awesome', category: 'life', tags: ['nature', 'growth', 'green'] },
    { value: 'iconify:fa6-solid:tree', label: 'Tree', set: 'Font Awesome', category: 'life', tags: ['nature', 'roots', 'growth'] },
    { value: 'iconify:fa6-solid:bicycle', label: 'Bicycle', set: 'Font Awesome', category: 'passion', tags: ['sport', 'travel', 'movement'] },
    { value: 'iconify:fa6-solid:person-running', label: 'Running', set: 'Font Awesome', category: 'passion', tags: ['sport', 'fitness', 'movement'] },
    { value: 'iconify:fa6-solid:person-swimming', label: 'Swimming', set: 'Font Awesome', category: 'passion', tags: ['sport', 'water', 'fitness'] },
    { value: 'iconify:fa6-solid:cat', label: 'Cat', set: 'Font Awesome', category: 'life', tags: ['pet', 'animal', 'family'] },
    { value: 'iconify:fa6-solid:baby', label: 'Baby', set: 'Font Awesome', category: 'life', tags: ['child', 'family', 'dad'] },
    { value: 'iconify:fa6-solid:ring', label: 'Ring', set: 'Font Awesome', category: 'life', tags: ['marriage', 'wedding', 'love'] },
    { value: 'iconify:fa6-solid:face-smile', label: 'Smile', set: 'Font Awesome', category: 'life', tags: ['happy', 'emotion', 'joy'] },
    { value: 'iconify:fa6-solid:face-frown', label: 'Frown', set: 'Font Awesome', category: 'pivotal', tags: ['sad', 'hard', 'emotion'] },
    { value: 'iconify:fa6-brands:github', label: 'GitHub', set: 'Font Awesome Brands', category: 'work', tags: ['code', 'software', 'open source'] },
    { value: 'iconify:fa6-brands:linkedin', label: 'LinkedIn', set: 'Font Awesome Brands', category: 'work', tags: ['career', 'network', 'profile'] },
    { value: 'iconify:fa6-brands:microsoft', label: 'Microsoft', set: 'Font Awesome Brands', category: 'work', tags: ['work', 'msn', 'software'] },
    { value: 'iconify:fa6-brands:x-twitter', label: 'X / Twitter', set: 'Font Awesome Brands', category: 'work', tags: ['social', 'community'] },
    { value: 'iconify:fa6-brands:youtube', label: 'YouTube', set: 'Font Awesome Brands', category: 'passion', tags: ['video', 'media'] },
    { value: 'iconify:mdi:school', label: 'School', set: 'Material Design', category: 'work', tags: ['education', 'learning', 'class'] },
    { value: 'iconify:mdi:account-star', label: 'Account Star', set: 'Material Design', category: 'work', tags: ['person', 'recognition', 'achievement'] },
    { value: 'iconify:mdi:account-tie', label: 'Account Tie', set: 'Material Design', category: 'work', tags: ['career', 'professional', 'job'] },
    { value: 'iconify:mdi:account-group', label: 'Account Group', set: 'Material Design', category: 'life', tags: ['people', 'team', 'community'] },
    { value: 'iconify:mdi:account-multiple', label: 'Account Multiple', set: 'Material Design', category: 'life', tags: ['people', 'team', 'social'] },
    { value: 'iconify:mdi:hand-heart', label: 'Hand Heart', set: 'Material Design', category: 'life', tags: ['care', 'support', 'love'] },
    { value: 'iconify:mdi:charity', label: 'Charity', set: 'Material Design', category: 'passion', tags: ['volunteer', 'giving', 'community'] },
    { value: 'iconify:mdi:home', label: 'Home', set: 'Material Design', category: 'life', tags: ['house', 'family', 'place'] },
    { value: 'iconify:mdi:earth', label: 'Earth', set: 'Material Design', category: 'pivotal', tags: ['world', 'global', 'travel'] },
    { value: 'iconify:mdi:map-marker', label: 'Map Marker', set: 'Material Design', category: 'life', tags: ['location', 'place', 'travel'] },
    { value: 'iconify:mdi:airplane', label: 'Airplane', set: 'Material Design', category: 'life', tags: ['travel', 'flight'] },
    { value: 'iconify:mdi:robot', label: 'Robot', set: 'Material Design', category: 'work', tags: ['ai', 'automation', 'technology'] },
    { value: 'iconify:mdi:lightbulb-on', label: 'Lightbulb On', set: 'Material Design', category: 'pivotal', tags: ['idea', 'insight'] },
    { value: 'iconify:mdi:arrow-up-bold-circle', label: 'Arrow Up Circle', set: 'Material Design', category: 'work', tags: ['growth', 'progress', 'next level'] },
    { value: 'iconify:mdi:numeric-1-box-multiple', label: 'Number One Boxes', set: 'Material Design', category: 'work', tags: ['million', 'scale', 'achievement'] },
    { value: 'iconify:mdi:package-variant', label: 'Package Variant', set: 'Material Design', category: 'passion', tags: ['crate', 'box', 'shipping'] },
    { value: 'iconify:mdi:bucket-outline', label: 'Bucket', set: 'Material Design', category: 'life', tags: ['bucket list', 'goal', 'travel'] },
    { value: 'iconify:mdi:flag-checkered', label: 'Checkered Flag', set: 'Material Design', category: 'basic', tags: ['finish', 'end', 'goal'] },
    { value: 'iconify:mdi:microsoft', label: 'Microsoft', set: 'Material Design', category: 'work', tags: ['work', 'msn', 'software'] },
    { value: 'iconify:mdi:pencil', label: 'Pencil', set: 'Material Design', category: 'passion', tags: ['write', 'edit', 'story'] },
    { value: 'iconify:mdi:run', label: 'Run', set: 'Material Design', category: 'passion', tags: ['sport', 'fitness'] },
    { value: 'iconify:mdi:swim', label: 'Swim', set: 'Material Design', category: 'passion', tags: ['sport', 'water'] },
    { value: 'iconify:mdi:beach', label: 'Beach', set: 'Material Design', category: 'life', tags: ['travel', 'water', 'holiday'] },
    { value: 'iconify:mdi:tools', label: 'Tools', set: 'Material Design', category: 'passion', tags: ['making', 'repair', 'builder'] },
    { value: 'iconify:mdi:hammer-wrench', label: 'Hammer Wrench', set: 'Material Design', category: 'passion', tags: ['tools', 'building', 'making'] },
    { value: 'iconify:mdi:palette', label: 'Palette', set: 'Material Design', category: 'passion', tags: ['art', 'creative', 'design'] },
    { value: 'iconify:mdi:camera', label: 'Camera', set: 'Material Design', category: 'passion', tags: ['photo', 'memory'] },
    { value: 'iconify:mdi:book-open-page-variant', label: 'Open Book', set: 'Material Design', category: 'passion', tags: ['read', 'learn', 'story'] },
    { value: 'iconify:mdi:heart', label: 'Heart', set: 'Material Design', category: 'life', tags: ['love', 'family'] },
    { value: 'iconify:mdi:medal-outline', label: 'Medal Outline', set: 'Material Design', category: 'work', tags: ['award', 'sport', 'recognition'] },
    { value: 'iconify:mdi:alpha-x-circle-outline', label: 'X Circle', set: 'Material Design', category: 'work', tags: ['xero', 'brand', 'work'] },
    { value: 'iconify:lucide:compass', label: 'Compass', set: 'Lucide', category: 'pivotal', tags: ['direction', 'travel', 'choice'] },
    { value: 'iconify:lucide:milestone', label: 'Milestone', set: 'Lucide', category: 'basic', tags: ['timeline', 'marker', 'achievement'] },
    { value: 'iconify:lucide:sparkles', label: 'Sparkles', set: 'Lucide', category: 'pivotal', tags: ['magic', 'new', 'special'] },
    { value: 'iconify:lucide:badge-check', label: 'Badge Check', set: 'Lucide', category: 'work', tags: ['verified', 'done', 'achievement'] },
    { value: 'iconify:lucide:network', label: 'Network', set: 'Lucide', category: 'work', tags: ['social', 'connections', 'system'] },
    { value: 'iconify:lucide:cpu', label: 'CPU', set: 'Lucide', category: 'work', tags: ['technology', 'ai', 'hardware'] },
    { value: 'iconify:lucide:boxes', label: 'Boxes', set: 'Lucide', category: 'passion', tags: ['crate', 'package', 'making'] },
    { value: 'iconify:lucide:tent-tree', label: 'Tent Tree', set: 'Lucide', category: 'life', tags: ['outdoors', 'travel', 'adventure'] },
    { value: 'iconify:lucide:ship-wheel', label: 'Ship Wheel', set: 'Lucide', category: 'pivotal', tags: ['direction', 'journey', 'sea'] },
    { value: 'iconify:ph:rocket-launch', label: 'Rocket Launch', set: 'Phosphor', category: 'work', tags: ['launch', 'startup', 'growth'] },
    { value: 'iconify:ph:brain', label: 'Brain', set: 'Phosphor', category: 'pivotal', tags: ['learning', 'thinking', 'mind'] },
    { value: 'iconify:ph:plant', label: 'Plant', set: 'Phosphor', category: 'life', tags: ['growth', 'nature'] },
    { value: 'iconify:ph:hand-heart', label: 'Hand Heart', set: 'Phosphor', category: 'life', tags: ['care', 'support', 'love'] },
    { value: 'iconify:ph:users-three', label: 'Users Three', set: 'Phosphor', category: 'life', tags: ['people', 'team', 'community'] },
    { value: 'iconify:ph:briefcase', label: 'Briefcase', set: 'Phosphor', category: 'work', tags: ['career', 'job'] },
    { value: 'iconify:ph:lightbulb', label: 'Lightbulb', set: 'Phosphor', category: 'pivotal', tags: ['idea', 'insight'] },
    { value: 'iconify:ph:globe-hemisphere-east', label: 'Globe Hemisphere', set: 'Phosphor', category: 'pivotal', tags: ['world', 'travel'] },
    { value: 'iconify:ph:package', label: 'Package', set: 'Phosphor', category: 'passion', tags: ['box', 'crate', 'shipping'] },
    { value: 'iconify:ph:medal', label: 'Medal', set: 'Phosphor', category: 'work', tags: ['award', 'achievement'] }
  ];

  window.ICON_CATALOG = icons.map(function (icon) {
    return Object.assign({ class: icon.value }, icon);
  });
  window.FA_ICONS = window.ICON_CATALOG;
}());
